config/routes.rb
Rails.application.routes.draw do
  get 'edu' => 'welcome#edu'

  get 'exp' => 'welcome#exp'

  get 'proj' => 'welcome#proj'

  get 'img' => 'welcome#img'

  get 'home' => 'welcome#home'

  get 'skill' => 'welcome#skill'

  root to: 'welcome#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def edu
    @cog_str = "edu"
  end

  def exp
    @cog_str = "exp"
  end

  def proj
    @cog_str = "proj"
  end

  def img
    @cog_str = "img"
  end

  def skill
    @cog_str = "skill"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Benjamin Bao</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id='name'><p>************************* Benjamin Yuyang Bao *************************</p></div>
<div id='profileInfo'>
  <img id='profileInfoImg' width="135" height="135" src="assets/profile.jpg" alt='profile picture, too bad'></img>
  <div id='profileInfoText'>
    {
    <p><span class='h_oneTab'>Intro: 'I'm Ben, a crazy computer euthusiast!</br><span class='h_introTab'>I'm currently a UCLA ugrad senior student,</span></br><span class='h_introTab'>welcome to my website!',</span></span></br></br><span class='h_oneTab'>Email: 'byyagp@gmail.com', </span></br> <span class='h_oneTab'>Cell: '+13109139124',</span></br> <span class='h_oneTab'>Address: '10933 Rochester Ave, Apt 416'</span></br>}</p>
  </div>
</div>


<!-- this is for the nav bar -->
<div id="profileIcon">

  <p>> <%= link_to("EDUCATION", edu_path) %> <%= fa_icon('cog spin') if @cog_str == "edu"%></p>
  <p>> <%= link_to("EXPERIENCE", exp_path) %> <%= fa_icon('cog spin') if @cog_str == "exp"%></p>
  <p>> <%= link_to("PROJECT & IDEAS", proj_path) %> <%= fa_icon('cog spin') if @cog_str == "proj"%></p>
  <p>> <%= link_to("SKILLS", skill_path) %> <%= fa_icon('cog spin') if @cog_str == "skill"%></p>
  <p>> <%= link_to("ART & DESIGN", img_path) %> <%= fa_icon('cog spin') if @cog_str == "img"%></p>

</div>
  <p>***********************************************************************</p>
  <br>

<%= yield %>

<div id='footer'>
  <p>***********************************************************************</p>
  <br>

  <h4>Statistics:</h4>
  <ul id='footerStats'>
    <li>Page Views: </li>
    <li>You are the 20th visitor! Thanks!</li>
  </ul>

  <ul id='footerMenu'>
    <li><%= link_to("EDUCATION", edu_path)%> <%= fa_icon('cog spin') if @cog_str == "edu"%></li>
    <li><%= link_to("EXPERIENCE", exp_path) %> <%= fa_icon('cog spin') if @cog_str == "exp"%></li>
    <li><%= link_to("PROJECT & IDEAS", proj_path) %> <%= fa_icon('cog spin') if @cog_str == "proj"%></li>
    <li><%= link_to("SKILLS", skill_path) %> <%= fa_icon('cog spin') if @cog_str == "skill"%></li>
    <li><%= link_to("ART & DESIGN", img_path) %> <%= fa_icon('cog spin') if @cog_str == "img"%></li>
  </ul>

  <p></p>
</div>

</body>
</html>

app/views/welcome/edu.html.erb
<div id="education">
  <p class='educationTitle'>EDUCATION [<button class='buttons' id='buttonOne'><%= fa_icon('angle-double-down')%></button></br>{</p>
  <p class="educationName">
    <span class='h_oneTab'>College: '<span class='span_bold'>UCLA</span>',</span>
  </p>

  <ul class="educationList">
    <li><span class='h_oneTab'>Major: '<span class='span_bold'>B.S. in Mathematics of Computation<span>',</span></li>
    <li><span class='h_oneTab'>Major GPA: '<span class='span_bold'>3.7/4<span>',</span></li>
    <div class='responderOne'>
    <li><span class='h_oneTab'>Major Courses taken: {
      <ul class='educationListCourse'>
        <li>1: 'Math 32a, 32b: Multivariable Calculus',</li>
        <li>2: 'Math 33a: Intro to Linear Algebra',</li>
        <li>3: 'Math 33b: Differential Equation',</li>
        <li>4: 'Physics 1a: Mechanics',</li>
        <li>5: 'Physics 1b: Wave and Oscillation',</li>
        <li>6: 'Chem 20A: Atomic Structure',</li>
        <li>7: 'PIC 10a,b,c: Intro/Intermediate/Advanced C++',</li>
        <li>8: 'PIC 40a: Web Programming',</li>
        <li>9: 'Math 115A: Linear Algebra',</li>
        <li>10: 'Math 131A: Real Analysis',</li>
        <li>11: 'Math 132: Complex Analysis',</li>
        <li>12: 'Math 134: Nonlinear System',</li>
        <li>13: 'Math 142: Mathematical Modeling',</li>
        <li>14: 'Math 151A: Numerical Methods',</li>
        <li>15: 'Math 155: Digital Image Processing',</li>
        <li>16: 'Math 164: Optimization',</li>
        <li>17: 'Math 170a,b: Probability Theory',</li>
        <li>18: 'CS 118: Computer Network',</li>
        <li>19: 'CS 143:  Database Management System',</li>
        <li>20: 'CS 170A: Computer Methods',</li>
        <li>21: 'CS 180: Algorithm and Complexity'</li>
      </ul><span class='h_oneTab'>}</span>
    </li></span></div>
  </ul>},




  <p class="educationName" id="educationNameSecond">
      <p>{</p>
      <span class='h_oneTab'>College: '<span class='span_bold'>Yale University</span>',</span>
  </p>

  <ul class="educationList">
    <li><span class='h_oneTab'>Program: 'Summer Program, 2014',</span></li>
    <div class='responderOne'>
    <li><span class='h_oneTab'>Courses: {
      <ul class='educationListCourse'>
        <li>1: 'Mathematical Logic'</li>
      </ul><span class='h_oneTab'>}</span>
    </span></li></div>
    
  </ul>}]
</div>
<script type="text/javascript">
  
  $.fn.slideFadeToggle = function(){
    return this.animate({ opacity: 'toggle', height: 'toggle' }, 350, 'swing');
  };

  var rotateOne = false;
  $('#buttonOne').on('click', function(){
    $('.responderOne').slideFadeToggle();
    if(!rotateOne)
    {
      $('#buttonOne').addClass('rotate');
      rotateOne = true;
    }
    else
    {
      $('#buttonOne').removeClass('rotate');
      rotateOne = false;
    }
  });
</script>

app/views/welcome/exp.html.erb
<div id="education">
  <p class='educationTitle'>EXPERIENCE [<button class='buttons' id='buttonTwo'><%= fa_icon('angle-double-down')%></button></br>{</p>

  <ul class="educationList">
    <li><span class='h_oneTab'>Role: 'Team Initiator/Technical Director',</span></li>
    <li><span class='h_oneTab'>Company: 'UCLA Startup',</span></li>
    <li><span class='h_oneTab'>Industry: 'Startup & Software',</span></li>
    <li><span class='h_oneTab'>Time: '2013.5 -',</span></li>
    <div class='responderTwo'>
    <li><span class='h_oneTab'>What I acheived: {
      <ul class='educationListCourse'>
        <li>1: 'Wrote a 2000-line console application (in C++) to simulate the basketball ranking system, which ranks the basketball enthusiasts based on their statistics on court, and also provides functionalities including “Find a Match”, “Find a Court” etc.',</li> <br>
        <li>2: 'Pitch the blueprint of project Hierarchy to UCLA Startup and got into the second round.',</li> <br>
        <li>3: 'Did front-end design(UI/UX) for 10 pages of application and back-end (users and databases) design on “Hierarchy”',</li>
      </ul><span class='h_oneTab'>}</span>
    </li></span></div>},
  </ul>
  <br>{
  <ul class="educationList">
    <li><span class='h_oneTab'>Role: 'Project Specialist',</span></li>
    <li><span class='h_oneTab'>Company: 'SAP',</span></li>
    <li><span class='h_oneTab'>Industry: 'IT & Software',</span></li>
    <li><span class='h_oneTab'>Time: '2014.6 - 2014.9',</span></li>
    <div class='responderTwo'>
    <li><span class='h_oneTab'>What I acheived: {
      <ul class='educationListCourse'>
        <li>1: 'Created and maintained roles and authorization in about 5 SAP modules (SAP ECC, BW, GTS, DU1, PU1...) through SAP NetWeaver including Transaction Codes: SU01, SU10, PFCG, SE16, SM12, SUIM',</li> <br>
        <li>2: 'Helped designing and analyzing the risks/conflicts of nearly 200 composite roles for Cardinal Health Inc during project Penguin',</li> <br>
        <li>3: 'Processed numbers of tickets and role requests by performing the role analysis and system simulations in PM1',</li>
      </ul><span class='h_oneTab'>}</span>
    </li></span></div>},
  </ul>

  <br>{
  <ul class="educationList">
    <li><span class='h_oneTab'>Role: 'Web Developer',</span></li>
    <li><span class='h_oneTab'>Company: 'SchooLinks Inc',</span></li>
    <li><span class='h_oneTab'>Industry: 'Internet',</span></li>
    <li><span class='h_oneTab'>Time: '2014.4 - 2014.6',</span></li>
    <div class='responderTwo'>
    <li><span class='h_oneTab'>What I acheived: {
      <ul class='educationListCourse'>
        <li>1: 'Revamped the entire database structure with teammates by rebuilding the Entity-Relationship Diagram from scratch containing 5 main categories, 87 database tables with approximately 500 data fields.',</li> <br>
        <li>2: 'Formulated a comprehensive Google SEO strategies by efficiently organizing the approximately 100 path names of web pages, speeding up the site loading time by various techniques like “combining css”, “deferring javascript” etc, refining keyword searching (title, meta-tags and footer), and resolving crawl errors (including server errors, web page errors etc).',</li> <br>
        <li>3: 'Designed and carried out 20 email templates through HTML and CSS, and implement them with Mandrill API in the back-end.',</li> <br>
        <li>4: 'Come up with several new features and layouts including “departments”, “company pages”, “my chances” etc.',</li> <br>
        <li>5: 'Created a 5-star-rating ranking algorithm (in php), which utilizes Wilson Confidence algorithm and eliminates outliers.',</li>
      </ul><span class='h_oneTab'>}</span>
    </li></span></div>},
  </ul>

  <br>{
  <ul class="educationList">
    <li><span class='h_oneTab'>Role: 'Project Specialist',</span></li>
    <li><span class='h_oneTab'>Company: 'English First',</span></li>
    <li><span class='h_oneTab'>Industry: 'IT',</span></li>
    <li><span class='h_oneTab'>Time: '2012.6 - 2012.9',</span></li>
    <div class='responderTwo'>
    <li><span class='h_oneTab'>What I acheived: {
      <ul class='educationListCourse'>
        <li>1: 'Wrote approximately 15 database files of teaching content and audio materials in JSON format, and connect the backend data to the IOS application “Engage” through its API.',</li> <br>
        <li>2: 'Implementing Amazon cloud server EC3, S3 and participating in deciding database structure for iOS application “Engage”.',</li> <br>
        <li>3: 'Designed and carried out 20 email templates through HTML and CSS, and implement them with Mandrill API in the back-end.',</li>
      </ul><span class='h_oneTab'>}</span>
    </li></span>},</div>
  </ul>
</div>

<script type="text/javascript">
  
  $.fn.slideFadeToggle = function(){
    return this.animate({ opacity: 'toggle', height: 'toggle' }, 350, 'swing');
  };

  var rotateTwo = false;
  $('#buttonTwo').on('click', function(){
    $('.responderTwo').slideFadeToggle();
    if(!rotateTwo)
    {
      $('#buttonTwo').addClass('rotate');
      rotateTwo = true;
    }
    else
    {
      $('#buttonTwo').removeClass('rotate');
      rotateTwo = false;
    }
  });
</script>

app/views/welcome/home.html.erb
<div id="home">
  <br><br>
  <h1>This is my homepage!</h1>
</div>

app/views/welcome/img.html.erb
<div id="img">
  <p>These are the work that I've done! (some laptap murals and amature logo designs, feel free to click for larger image ;)</p>
  <br><br>
  <button class='buttons' id='buttonPattern'><%= fa_icon('angle-double-down')%></button>
  <p>> Patterns: </p>
  <br>

  <div class='responderPattern'>
    <table style="width:100%" class="imgTable">
      <tr>
        <td><%= link_to image_tag("img1.jpg", :alt => "rss feed", width:"300", height:"200"),image_path("img1.jpg"), rel: :lazybox, :title => 'This is me!'%></td>
        <td><%= link_to image_tag("img2.jpg", :alt => "rss feed", width:"300", height:"200"),image_path("img2.jpg"), rel: :lazybox%></td>
      </tr>
      <tr>
        <td><%= link_to image_tag("img3.jpg", :alt => "rss feed", width:"300", height:"210"),image_path("img3.jpg"), rel: :lazybox%></td>
        <td><%= link_to image_tag("img4.jpg", :alt => "rss feed", width:"300", height:"190"),image_path("img4.jpg"), rel: :lazybox%></td>
      </tr>
      <tr>
        <td><%= link_to image_tag("p2.jpg", :alt => "rss feed", width:"300", height:"200"),image_path("p2.jpg"), rel: :lazybox%></td>
        <td><%= link_to image_tag("p1.jpg", :alt => "rss feed", width:"300", height:"362"),image_path("p1.jpg"), rel: :lazybox%></td>
      </tr>
      <tr>
        <td><%= link_to image_tag("p3.jpg", :alt => "rss feed", width:"300", height:"356"),image_path("p3.jpg"), rel: :lazybox%></td>
        <td><%= link_to image_tag("p4.jpg", :alt => "rss feed", width:"300", height:"368"),image_path("p4.jpg"), rel: :lazybox%></td>
      </tr>
    </table> 
  </div>

  <br><br><button class='buttons' id='buttonLogo'><%= fa_icon('angle-double-down')%></button>
  <p>> Logo Design: </p>
  <br>

  <div class='responderLogo'>
    <table style="width:100%" class="imgTable">
      <tr>
        <td><%= link_to image_tag("jct.png", :alt => "rss feed", width:"300", height:"100"),image_path("jct.png"), rel: :lazybox%></td>
        <td><%= link_to image_tag("img6.png", :alt => "rss feed", width:"300", height:"175"),image_path("img6.png"), rel: :lazybox%></td>
      </tr>
      <tr>
        <td><%= link_to image_tag("img7.png", :alt => "rss feed", width:"300", height:"185"),image_path("img7.png"), rel: :lazybox%></td>
        <td><%= link_to image_tag("img8.png", :alt => "rss feed", width:"300", height:"185"),image_path("img8.png"), rel: :lazybox%></td>
      </tr>
    </table>
  </div>

  <br><br><button class='buttons' id='buttonWeb'><%= fa_icon('angle-double-down')%></button>
  <p>> Webpage Designs: </p>
  <br>

  <div class='responderWeb'>
    <table style="width:100%" class="imgTable">
      <tr>
        <td><%= link_to image_tag("longWeb.jpg", :alt => "rss feed", width:"630", height:"1000"),image_path("longWeb.jpg"), rel: :lazybox%></td>
      </tr>
    </table> 
  </div>

  <br><br><button class='buttons' id='buttonDrawing'><%= fa_icon('angle-double-down')%></button>
  <p>> Drawing: </p>
  <br>

  <div class='responderDrawing'>
    <table style="width:100%" class="imgTable">
      <tr>
        <td><%= link_to image_tag("d1.jpg", :alt => "rss feed", width:"300", height:"380"),image_path("d1.jpg"), rel: :lazybox%></td>
        <td><%= link_to image_tag("d2.jpg", :alt => "rss feed", width:"300", height:"400"),image_path("d2.jpg"), rel: :lazybox%></td>
      </tr>
    </table> 
  </div>
</div>


<script type="text/javascript">
  
  $.fn.slideFadeToggle = function(){
    return this.animate({ opacity: 'toggle', height: 'toggle' }, 350, 'swing');
  };

  function toggle(buttonId, responderId){
    var rotate = false;
    $(buttonId).on('click', function(){
    $(responderId).slideFadeToggle();
    if(!rotate)
    {
      $(buttonId).addClass('rotate');
      rotate = true;
    }
    else
    {
      $(buttonId).removeClass('rotate');
      rotate = false;
    }
  });
  }
  
  toggle('#buttonPattern', '.responderPattern');
  toggle('#buttonLogo', '.responderLogo');
  toggle('#buttonWeb', '.responderWeb');
  toggle('#buttonDrawing', '.responderDrawing');

</script>

app/views/welcome/proj.html.erb
<div>
  <p>Integer Partition Qt C++ project</p><button class='buttons' id='buttonThree'><%= fa_icon('angle-double-down')%></button><br>
  <p class='h_oneTab'> ---- with Professor Stephen DeSalvo, UCLA</p>
  <div class='responderThree'>
  <ul class='educationListCourse'>
    <li>* Build a Qt based on C++ cross-plaqorm application to perform 8 basic transformation of Integer Partitions and display the corresponding Ferrers Diagram, including Move, Shift, Cut, Paste, Union, Sum, Shred and Stretch.</li> <br>
    <li class="customLink">* For the documentation of the transformation of Integer Partitions, pls visit the paper by Professor Pak <%= link_to "<< Asymptotic Stability - Igor Pak >>", "http://www.math.ucla.edu/~pak/papers/stab5.pdf", :target => "_blank"%></li> <br>
    <li class="customLink">* Here is the source code on Github: <%= link_to "Source Code", "https://github.com/rouchailatte/IntPartProj", :target => "_blank"%></li>
  </ul></div>
  <br><br>
  <p>Corporate Culture Consulting Analyst</p><br>
  <p class='h_oneTab'> ---- with Professor Eric Flamholtz, UCLA</p>
  <div class='responderThree'>
  <ul class='educationListCourse'>
    <li>* Launched numbers of questionnaires and approximately 15 interviews with employees of all positions and extracted the data.</li><br>
    <li>* Calculate the correlation index between these two factors by using various statistical methods including “regression analysis”.</li>
  </ul></div>
  <br><br>
  <p>The Project Hub Idea</p>
  <div class='responderThree'>
    <ul class='educationListCourse'>
      <li>* Create a online hub for academic projects and idea exchange</li>
      <li>* Working on the basic idea and model right now..</li>
    </ul>
  </div>
</div>

<script type="text/javascript">
  
  $.fn.slideFadeToggle = function(){
    return this.animate({ opacity: 'toggle', height: 'toggle' }, 350, 'swing');
  };


  function toggle(buttonId, responderId){
    var rotate = false;
    $(buttonId).on('click', function(){
    $(responderId).slideFadeToggle();
    if(!rotate)
    {
      $(buttonId).addClass('rotate');
      rotate = true;
    }
    else
    {
      $(buttonId).removeClass('rotate');
      rotate = false;
    }
  });

  }

  toggle('#buttonThree', '.responderThree');

</script>

app/views/welcome/skill.html.erb
<div>
  <button class='buttons' id='buttonFour'><%= fa_icon('angle-double-down')%></button>
  <p>Computer Science Skills:</p>
  <div class='responderFour'>
  <ul class='educationListCourse'>
    <li>Proficient: C++</li>
    <li>Very Solid in: Mathematics</li>
    <li>Good at: Java, DBMS, SQL, Ruby on Rails, Java Servlet, HTML, CSS, javascript</li>
    <li>Familiar with: C, php, Python, Unix Shell, Network Programming, MATLAB, Git</li>
    <li>Interested in: Network, Mobile System, AI, Computer Vision</li>
  </ul>
  </div>
  <br><br>
  <p>Other Hobbies:</p>
  <div class='responderFour'>
  <ul class='educationListCourse'>
    <li class="customLink">Amature logo graphic designer: <%= link_to "My DeviantArt", "http://callmeqwer.deviantart.com/", :target => "_blank"%></li>
    <li>DJ and Mixing, my mixing videos are coming out soon!</li>
    <li>Gamer (Dota, Diablo, Crysis, Skyrim, DJMax, Counter-Strike, Flappy Bird..)</li>
    <li>Skateboarding, Swimming, BasketBall, making music and creating all sorts of things!</li>
  </ul>
  </div>
</div>

<script type="text/javascript">
  
  $.fn.slideFadeToggle = function(){
    return this.animate({ opacity: 'toggle', height: 'toggle' }, 350, 'swing');
  };

  var rotateFour = false;
  $('#buttonFour').on('click', function(){
    $('.responderFour').slideFadeToggle();
    if(!rotateFour)
    {
      $('#buttonFour').addClass('rotate');
      rotateFour = true;
    }
    else
    {
      $('#buttonFour').removeClass('rotate');
      rotateFour = false;
    }
  });
</script>